-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 23:45:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema d-toke_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `d-toke_db` ;

-- -----------------------------------------------------
-- Schema d-toke_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `d-toke_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movies_db` ;

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `d-toke_db` ;

-- -----------------------------------------------------
-- Table `d-toke_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d-toke_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `image` VARCHAR(45) NULL,
  `price` INT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `d-toke_db`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d-toke_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d-toke_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_rols1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `d-toke_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d-toke_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(45) NOT NULL,
  `main` TINYINT NULL DEFAULT 0,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_products_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `d-toke_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d-toke_db`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `province` VARCHAR(255) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_addresses_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `d-toke_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d-toke_db`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d-toke_db`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` INT NULL,
  `createdAt` TIMESTAMP NULL,
  `users_id` INT NOT NULL,
  `statuses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_order_statusses1_idx` (`statuses_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `d-toke_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_statuses`
    FOREIGN KEY (`statuses_id`)
    REFERENCES `d-toke_db`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `d-toke_db`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d-toke_db`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_items_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_items_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `d-toke_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `d-toke_db`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `movies_db` ;

-- -----------------------------------------------------
-- Table `movies_db`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11;


-- -----------------------------------------------------
-- Table `movies_db`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE,
  INDEX `password_resets_token_index` (`token` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`sequelizemeta` (
  `name` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
